apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbwikijs
  namespace: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbwikijs
  template:
    metadata:
      labels:
        app: dbwikijs
    spec:
      containers:
      - name: dbwikijs
        image: postgres:14.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: db-config
        - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: db-config
        - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-pass 
                key: password 
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume-pvc
      volumes:
      - name: db-volume-pvc
        persistentVolumeClaim:
          claimName: db-volume-pvc