# Deployment do banco Postgres

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: wikiapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:14.1-alpine
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: db-config
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: db-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: db-pass
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume-pvc
      volumes:
      - name: db-volume-pvc
        persistentVolumeClaim:
          claimName: db-vol-pvc
