apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume-pv
  namespace: wikijs
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/server/k8s/wikijs/data"
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-pvc
  labels:
    app: dbwikijs
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi