# Volume percistente.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-vol-pv
  namespace: wikiapp
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
  storageClassName: manual
---
# Volume percistente claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-vol-pvc
  namespace: wikiapp 
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
